<?php

/* Ca c'est le manager comme en PhP on met les requetes/fonctions que ici */

namespace GestionParcInfo\ParcInfoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MaterielsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielsRepository extends EntityRepository
{
     public function getMaterielsHS()
    {
        $query = $this->getEntityManager()
                    ->createQuery('SELECT m FROM ParcInfoBundle:Materiels m WHERE m.numEtat = :num')
                    ->setParameter('num', 3);
        
        $materielsHS = $query->getResult();
        
        return $materielsHS;
    }
}
