<?php

namespace Proxies\__CG__\GestionParcInfo\ParcInfoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Materiel extends \GestionParcInfo\ParcInfoBundle\Entity\Materiel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'id', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'nomMat', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'dateGarantie', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'numSite', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'numEtat', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'numStatut', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'numHistorique', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'numCarac');
        }

        return array('__isInitialized__', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'id', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'nomMat', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'dateGarantie', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'numSite', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'numEtat', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'numStatut', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'numHistorique', '' . "\0" . 'GestionParcInfo\\ParcInfoBundle\\Entity\\Materiel' . "\0" . 'numCarac');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Materiel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomMat($nomMat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomMat', array($nomMat));

        return parent::setNomMat($nomMat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomMat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomMat', array());

        return parent::getNomMat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateGarantie($dateGarantie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateGarantie', array($dateGarantie));

        return parent::setDateGarantie($dateGarantie);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateGarantie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateGarantie', array());

        return parent::getDateGarantie();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumSite(\GestionParcInfo\ParcInfoBundle\Entity\Site $numSite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumSite', array($numSite));

        return parent::setNumSite($numSite);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumSite', array());

        return parent::getNumSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumEtat(\GestionParcInfo\ParcInfoBundle\Entity\Etat $numEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumEtat', array($numEtat));

        return parent::setNumEtat($numEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumEtat', array());

        return parent::getNumEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumStatut(\GestionParcInfo\ParcInfoBundle\Entity\Statut $numStatut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumStatut', array($numStatut));

        return parent::setNumStatut($numStatut);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumStatut', array());

        return parent::getNumStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumHistorique(\GestionParcInfo\ParcInfoBundle\Entity\Historique $numHistorique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumHistorique', array($numHistorique));

        return parent::setNumHistorique($numHistorique);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumHistorique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumHistorique', array());

        return parent::getNumHistorique();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumCarac(\GestionParcInfo\ParcInfoBundle\Entity\Caracteristique $numCarac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumCarac', array($numCarac));

        return parent::setNumCarac($numCarac);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumCarac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumCarac', array());

        return parent::getNumCarac();
    }

}
